### ISSUE TITLE
feat: implement /traveling-with-a-pet

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#133]
The goal here is to migrate https://www.petplace.com/traveling-with-a-pet/ to Franklin and re-implement the template and blocks for the page.

# Scope

## Links:

- Word document in Sharepoint for the page: [traveling-with-a-pet.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B61065362-F3D1-4E2C-8277-D4D98A455990%7D&file=traveling-with-a-pet.docx&action=default&mobileredirect=true)
- Page Url: https://main--petplace--hlxsites.hlx.page/drafts/xfeng/traveling-with-a-pet

## Tasks

- [x] #139
- [x] Identify the individual sections and blocks required to design the page
  - The Table-of-Content links at the top
  - The types icon bar
  - etc.
- [x] Identify what existing blocks we can re-use and create variants for
- [x] Create a new template JS file for the page in `/templates` following the model of the existing ones
- [x] Implement individual blocks as needed in `/blocks`

This is meant as a wrapper story and we can extract individual bite-size tickets from this as needed.

# Screenshots

## Mobile

<img width="200" src="https://github.com/hlxsites/petplace/assets/1235810/9d5c2ad5-8fc9-46b3-8d25-9003b5b5b187"/><img width="200" src="https://github.com/hlxsites/petplace/assets/1235810/e347e876-2012-4e20-bd29-e013c66fd794"/><img width="200" src="https://github.com/hlxsites/petplace/assets/1235810/0fa1fd43-4898-4360-90be-14fd9a549a42"/><img width="200" src="https://github.com/hlxsites/petplace/assets/1235810/897ff943-8133-4f2a-baba-a85cd5e1c465"/> 

## Tablet

<img width="400" src="https://github.com/hlxsites/petplace/assets/1235810/ae7db3ef-62af-4674-8db8-8d2773359207"/>
<img width="400" src="https://github.com/hlxsites/petplace/assets/1235810/f705e2e9-5955-4a42-9a58-36e9b29c4125"/>
<img width="400" src="https://github.com/hlxsites/petplace/assets/1235810/f87b3aa8-4c23-4567-b78c-050d5f5fea43"/>
<img width="400" src="https://github.com/hlxsites/petplace/assets/1235810/795935a0-1ac4-436a-914e-5cc1f2f7bfb6"/>

## Desktop

![Image](https://github.com/hlxsites/petplace/assets/1235810/3bb072d6-565d-43a7-80e5-40baacdbf314)
![Image](https://github.com/hlxsites/petplace/assets/1235810/9c917360-825b-4646-afc0-df78f7f7973c)
![Image](https://github.com/hlxsites/petplace/assets/1235810/0c052b99-623b-445d-8aee-6365586583bc)
