### ISSUE TITLE
feat: pre go-live checklist

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#186]
See: https://www.hlx.live/docs/go-live-checklist

- [x] #197
- [x] #198
- [x] Validate martech tracking (analytics, etc.)
- [x] #89 
- [x] #188 
- [x] #189 
- [x] Favicon
- [x] CDN Configuration:
  - [x] https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/issues/53
  - [x] https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/issues/55
 - [x] Push Invalidation Setup => does not apply
 - [x] Update Production Host: https://github.com/hlxsites/petplace/pull/199
