### ISSUE TITLE
feat: post go-live checklist

### ISSUE THREAD

**Issue by ramboz** [hlxsites/petplace#187]
See: https://www.hlx.live/docs/go-live-checklist#post-go-live-validation

- [x] Performance Validation via CrUX (field) data
- [ ] Address Google Search Console issues
- [ ] Fix 404 links
- [x] Fix remaining UAT links

**Comment by ramboz** [comment]
Fix links for:

[petplace.com-organic-keywords-subdomains-us__2023-08-30_14-27-39.csv](https://github.com/hlxsites/petplace/files/12480343/petplace.com-organic-keywords-subdomains-us__2023-08-30_14-27-39.csv)
[petplace.com-backlinks-subdomains__2023-08-30_14-15-23.csv](https://github.com/hlxsites/petplace/files/12480344/petplace.com-backlinks-subdomains__2023-08-30_14-15-23.csv)

**Comment by ramboz** [comment]
Also addressing:


[Overview — Petplace.pdf](https://github.com/hlxsites/petplace/files/12480499/Overview.Petplace.pdf)

- [Top orphaned pages](https://github.com/hlxsites/petplace/files/12480500/petplace_29-aug-2023_orphan-page-.has-no-inco_2023-08-30_15-02-36.csv)
- [Top 4xx](https://github.com/hlxsites/petplace/files/12480501/petplace_29-aug-2023_4xx-page_2023-08-30_15-02-48.csv)
- [Top 404](https://github.com/hlxsites/petplace/files/12480502/petplace_29-aug-2023_4xx-page_2023-08-30_15-03-03.csv)
- [Top Pages with Broken Links](https://github.com/hlxsites/petplace/files/12480503/petplace_29-aug-2023_page-has-links-to-broken_2023-08-30_15-03-37.csv)
